# ── Production Database (Neon) ──
spring.datasource.url=jdbc:postgresql://ep-quiet-art-a43jju2p.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mW2Mkn9eagjc

# ── JPA ──
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ── JWT ──
app.jwt-secret=jp8W6eZm2izLfawAg0ZkWIp2Kudm1UP8V1ruzz6O5J4=