spring.application.name=medication-tracker-api

#default as dev
spring.profiles.active=dev

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.jwt-expiration-milliseconds=86400000

# actuator health point
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never