
spring.datasource.url=jdbc:postgresql://localhost:5432/medtracker
spring.datasource.username=postgres
spring.datasource.password=dukee2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt-secret=local_development_secret_key_must_be_very_long_to_be_secure_12345